
version: "3.8"
services:


  node_0:
    tty: true
    stdin_open: true
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      address: 127.0.0.1:8001
      type: 2 
      link: 127.0.0.1:8002
      VIS_ADDRESS: 127.0.0.1:8000/updateState
      requests: true
    ports:
      - "8001:8001"
    network_mode: host




  node_1:
    tty: true
    stdin_open: true
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      address: 127.0.0.1:8002
      type: 1 
      link: 
      VIS_ADDRESS: 127.0.0.1:8000/updateState
      requests: true
    ports:
      - "8002:8002"
    network_mode: host




  node_2:
    tty: true
    stdin_open: true
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      address: 127.0.0.1:8003
      type: 2 
      link: 127.0.0.1:8002
      VIS_ADDRESS: 127.0.0.1:8000/updateState
      requests: true
    ports:
      - "8003:8003"
    network_mode: host


